name: nchat
repo: d99kris/nchat
type: github_release # Método de verificação da versão
deps: >-
  git sudo lsb-release equivs golang libpng-dev libx11-dev libxcb1-dev
  libreadline-dev libssl-dev libncursesw5-dev libsqlite3-dev libmagic-dev
deb_depends: "libreadline8, libssl3, libncursesw6, libsqlite3-0, libmagic1, libxcb1"
build_cmd: |
  ./make.sh deps -y
  NCHAT_CMAKEARGS="-DCMAKE_INSTALL_PREFIX=/usr" ./make.sh build --no-telegram
  cd build
  make install DESTDIR=./prefix
description: Terminal-based Telegram and WhatsApp client
long_description: |
  nchat is a terminal-based chat client with support for Telegram
  and WhatsApp. It features a modern ncurses UI.
